"""add like dislike

Revision ID: 3923160b7a84
Revises: 
Create Date: 2026-06-14 11:41:55.222193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3923160b7a84'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_subscribers_id', table_name='subscribers')
    op.drop_table('subscribers')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_index('ix_users_id', table_name='users')
    op.drop_table('users')
    op.drop_table('access_tokens')
    op.drop_index('ix_two_factor_auth_id', table_name='two_factor_auth')
    op.drop_index('ix_two_factor_auth_user_id', table_name='two_factor_auth')
    op.drop_table('two_factor_auth')
    op.drop_index('ix_historys_id', table_name='historys')
    op.drop_table('historys')
    op.drop_index('ix_o_auth_account_id', table_name='o_auth_account')
    op.drop_index('ix_o_auth_account_provider', table_name='o_auth_account')
    op.drop_index('ix_o_auth_account_user_id', table_name='o_auth_account')
    op.drop_table('o_auth_account')
    op.drop_index('ix_audit_log_action', table_name='audit_log')
    op.drop_index('ix_audit_log_category', table_name='audit_log')
    op.drop_index('ix_audit_log_id', table_name='audit_log')
    op.drop_index('ix_audit_log_ip_address', table_name='audit_log')
    op.drop_index('ix_audit_log_user_id', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index('ix_refresh_token_expires_at', table_name='refresh_token')
    op.drop_index('ix_refresh_token_id', table_name='refresh_token')
    op.drop_index('ix_refresh_token_token', table_name='refresh_token')
    op.drop_index('ix_refresh_token_user_id', table_name='refresh_token')
    op.drop_table('refresh_token')
    op.drop_index('ix_role_id', table_name='role')
    op.drop_index('ix_role_name', table_name='role')
    op.drop_table('role')
    op.drop_table('user_roles')
    op.drop_index('ix_vidoss_id', table_name='vidoss')
    op.drop_table('vidoss')
    op.drop_index('ix_permission_category', table_name='permission')
    op.drop_index('ix_permission_id', table_name='permission')
    op.drop_index('ix_permission_name', table_name='permission')
    op.drop_table('permission')
    op.drop_table('role_permissions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role_permissions',
    sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('permission_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permission.id'], name='role_permissions_permission_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], name='role_permissions_role_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id', name='role_permissions_pkey')
    )
    op.create_table('permission',
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False, comment='Назва дозволу (формат: resource.action)'),
    sa.Column('display_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False, comment='Відображувана назва дозволу'),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True, comment='Опис дозволу'),
    sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=False, comment='Категорія дозволу (users, products, orders, etc.)'),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='permission_pkey')
    )
    op.create_index('ix_permission_name', 'permission', ['name'], unique=True)
    op.create_index('ix_permission_id', 'permission', ['id'], unique=False)
    op.create_index('ix_permission_category', 'permission', ['category'], unique=False)
    op.create_table('vidoss',
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('public_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('desc', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('author', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('file_path', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('file_size', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('content_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('vidoss_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('views', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('likes', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('dislikes', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='vidoss_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_vidoss_id', 'vidoss', ['id'], unique=False)
    op.create_table('user_roles',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], name='user_roles_role_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id', name='user_roles_pkey')
    )
    op.create_table('role',
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False, comment='Назва ролі (англійською, lowercase)'),
    sa.Column('display_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False, comment='Відображувана назва ролі'),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True, comment='Опис ролі'),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False, comment='Чи активна роль'),
    sa.Column('is_system', sa.BOOLEAN(), autoincrement=False, nullable=False, comment='Чи це системна роль (не можна видалити)'),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='role_pkey')
    )
    op.create_index('ix_role_name', 'role', ['name'], unique=True)
    op.create_index('ix_role_id', 'role', ['id'], unique=False)
    op.create_table('refresh_token',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False, comment='ID користувача'),
    sa.Column('token', sa.VARCHAR(length=500), autoincrement=False, nullable=False, comment='Refresh токен (хешований)'),
    sa.Column('device_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True, comment='ID пристрою користувача'),
    sa.Column('device_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True, comment='Назва пристрою (iPhone, Chrome на Windows, etc.)'),
    sa.Column('ip_address', sa.VARCHAR(length=45), autoincrement=False, nullable=True, comment='IP адреса при створенні токена'),
    sa.Column('user_agent', sa.TEXT(), autoincrement=False, nullable=True, comment='User Agent браузера'),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False, comment='Чи активний токен'),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False, comment='Дата закінчення токена'),
    sa.Column('last_used_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True, comment='Остання дата використання токена'),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='refresh_token_pkey')
    )
    op.create_index('ix_refresh_token_user_id', 'refresh_token', ['user_id'], unique=False)
    op.create_index('ix_refresh_token_token', 'refresh_token', ['token'], unique=True)
    op.create_index('ix_refresh_token_id', 'refresh_token', ['id'], unique=False)
    op.create_index('ix_refresh_token_expires_at', 'refresh_token', ['expires_at'], unique=False)
    op.create_table('audit_log',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True, comment='ID користувача (NULL якщо видалений)'),
    sa.Column('action', sa.VARCHAR(length=100), autoincrement=False, nullable=False, comment='Тип дії (user.login, user.register, role.assign, etc.)'),
    sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=False, comment='Категорія події (auth, users, roles, etc.)'),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True, comment='Опис події'),
    sa.Column('other_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='Додаткові дані події (JSON)'),
    sa.Column('ip_address', sa.VARCHAR(length=45), autoincrement=False, nullable=True, comment='IP адреса'),
    sa.Column('user_agent', sa.TEXT(), autoincrement=False, nullable=True, comment='User Agent'),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False, comment='Статус виконання (success, failed, warning)'),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True, comment='Повідомлення про помилку (якщо була)'),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='audit_log_pkey')
    )
    op.create_index('ix_audit_log_user_id', 'audit_log', ['user_id'], unique=False)
    op.create_index('ix_audit_log_ip_address', 'audit_log', ['ip_address'], unique=False)
    op.create_index('ix_audit_log_id', 'audit_log', ['id'], unique=False)
    op.create_index('ix_audit_log_category', 'audit_log', ['category'], unique=False)
    op.create_index('ix_audit_log_action', 'audit_log', ['action'], unique=False)
    op.create_table('o_auth_account',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False, comment='ID користувача'),
    sa.Column('provider', sa.VARCHAR(length=50), autoincrement=False, nullable=False, comment='Назва OAuth провайдера'),
    sa.Column('provider_user_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False, comment='ID користувача у провайдера'),
    sa.Column('provider_email', sa.VARCHAR(length=255), autoincrement=False, nullable=True, comment='Email отриманий від провайдера'),
    sa.Column('access_token', sa.TEXT(), autoincrement=False, nullable=True, comment='Access token від провайдера'),
    sa.Column('refresh_token', sa.TEXT(), autoincrement=False, nullable=True, comment='Refresh token від провайдера'),
    sa.Column('token_expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True, comment='Дата закінчення access token'),
    sa.Column('provider_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='Додаткові дані від провайдера (JSON)'),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False, comment='Чи активний OAuth акаунт'),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='o_auth_account_pkey')
    )
    op.create_index('ix_o_auth_account_user_id', 'o_auth_account', ['user_id'], unique=False)
    op.create_index('ix_o_auth_account_provider', 'o_auth_account', ['provider'], unique=False)
    op.create_index('ix_o_auth_account_id', 'o_auth_account', ['id'], unique=False)
    op.create_table('historys',
    sa.Column('viewer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('video_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['vidoss.id'], name='historys_video_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='historys_pkey')
    )
    op.create_index('ix_historys_id', 'historys', ['id'], unique=False)
    op.create_table('two_factor_auth',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False, comment='ID користувача'),
    sa.Column('secret', sa.VARCHAR(length=255), autoincrement=False, nullable=False, comment='Секретний ключ для генерації кодів'),
    sa.Column('is_enabled', sa.BOOLEAN(), autoincrement=False, nullable=False, comment='Чи увімкнена 2FA'),
    sa.Column('enabled_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True, comment='Дата активації 2FA'),
    sa.Column('backup_codes', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='Backup коди (хешовані)'),
    sa.Column('last_used_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True, comment='Дата останнього використання 2FA'),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='two_factor_auth_pkey')
    )
    op.create_index('ix_two_factor_auth_user_id', 'two_factor_auth', ['user_id'], unique=True)
    op.create_index('ix_two_factor_auth_id', 'two_factor_auth', ['id'], unique=False)
    op.create_table('access_tokens',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('token', sa.VARCHAR(length=43), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', 'token', name='access_tokens_pkey')
    )
    op.create_table('users',
    sa.Column('username', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=320), autoincrement=False, nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(length=1024), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_superuser', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_verified', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    sa.UniqueConstraint('username', name='users_username_key')
    )
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    op.create_table('subscribers',
    sa.Column('subscriber_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('subscribed_to_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='subscribers_pkey')
    )
    op.create_index('ix_subscribers_id', 'subscribers', ['id'], unique=False)
    # ### end Alembic commands ###
